"""Harness quality analyzer — scores Claude Code session transcripts.

Walks a session JSONL transcript, attributes tool errors, detects wasteful
patterns (duplicate commands, repeated reads, low scriptability, user
rejections), and produces a 0-100 score with a letter grade and
skill-tuning suggestions.

Scoring model: per-category subscores (0–100) combined by weights.
Each category subscore = 100 * max(0, 1 - rate / ref_rate), where ref_rate
is the rate at which the subscore hits 0. The overall score is the weighted
average of subscores, with a disaster guard: overall ≤ min_subscore + 45.

Ported and extended from a standalone session-scoring script. No third-party
deps; defensive against transcript schema drift.
"""

import json
import os
import re
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Optional

# ----------------------------------------------------------------------------
# Tunable scoring config. Transparent — edit weights to taste.
# ----------------------------------------------------------------------------
CONFIG = {
    # Category weights — must sum to 1.0
    "weights": {
        "errors": 0.30,
        "rejections": 0.25,
        "duplicate_commands": 0.20,
        "repeated_reads": 0.10,
        "scriptability": 0.15,
    },
    # Reference rates: the rate at which a category subscore hits 0.
    # e.g. errors ref 0.5 means half of all tool calls erroring → subscore 0.
    "ref_rates": {
        "errors": 0.50,          # tool_errors / total_tool_calls
        "rejections": 0.25,      # user_rejections / total_tool_calls
        "duplicate_commands": 0.50,  # extra dups / bash_calls
        "repeated_reads": 1.00,  # extra re-reads / read_calls
        # scriptability: binary_clusters / unique_binaries (fraction of unique
        # binaries that are "over-hammered"). 0.75 means 75% of unique binaries
        # each called ≥ threshold times → subscore 0.
        "scriptability": 0.75,
    },
    # Disaster guard: overall score ≤ min_subscore + this value.
    # Prevents a catastrophic category from being hidden by high others.
    "disaster_cap_addend": 45,
    # Minimum total_tool_calls for a meaningful grade; below this → low_activity.
    "min_tool_calls": 3,
    # if a single shell binary is invoked this many times, it should probably be
    # a script / a single batched call instead.
    "scriptability_threshold": 5,
    # Strict error text patterns, only used when a tool_result has no explicit
    # is_error key. Avoids matching benign phrases like "No errors found".
    "error_text_re": re.compile(
        r"(?m)"
        r"(Traceback \(most recent call last\)"
        r"|command not found"
        r"|^fatal:"
        r"|Permission denied"
        r"|No such file or directory"
        r"|^[Ee]rror:"
        r"|segmentation fault)",
    ),
    # Claude Code marks a denied tool call with this canned result text.
    "rejection_text_re": re.compile(
        r"(?i)(the user doesn'?t want to (?:proceed|take this action)|"
        r"user rejected|tool use was rejected|operation was (?:rejected|cancelled) by the user)"
    ),
    "grades": [  # (min_score, letter)
        (90, "A"), (80, "B"), (70, "C"), (60, "D"), (0, "F"),
    ],
}

TOOL_BLOCK_TYPES = {"tool_use", "tool_result"}

# Patterns for cleaning first_prompt output
_CAVEAT_PREFIX_RE = re.compile(
    r"^Caveat:\s+The messages below were generated by the user while running local commands[^\n]*\n?",
    re.IGNORECASE,
)
# XML-style blocks that are local-command / system infrastructure, not real prompts
_INFRA_TAG_RE = re.compile(
    r"<(?:command-name|command-message|local-command-stdout|system-reminder|task-notification)"
    r"[\s>].*?</(?:command-name|command-message|local-command-stdout|system-reminder|task-notification)>",
    re.DOTALL | re.IGNORECASE,
)
# Inline opening tags (self-closing or unclosed)
_INFRA_OPEN_TAG_RE = re.compile(
    r"</?(?:command-name|command-message|local-command-stdout|system-reminder|task-notification)[^>]*>",
    re.IGNORECASE,
)
_MULTI_SPACE_RE = re.compile(r"\s{2,}")
_XML_TAG_RE = re.compile(r"<[^>]+>")


# ----------------------------------------------------------------------------
# Transcript parsing — defensive against schema drift.
# ----------------------------------------------------------------------------
def _iter_lines(path: Path):
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def _walk_blocks(obj):
    """Yield every dict that looks like a tool_use / tool_result block, anywhere."""
    if isinstance(obj, dict):
        if obj.get("type") in TOOL_BLOCK_TYPES:
            yield obj
        for v in obj.values():
            yield from _walk_blocks(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _walk_blocks(v)


def _text_of(content) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for b in content:
            if isinstance(b, dict):
                if "text" in b:
                    parts.append(str(b.get("text", "")))
                elif b.get("type") == "tool_result":
                    parts.append(_text_of(b.get("content")))
        return "\n".join(parts)
    return ""


def _first_token(cmd: str) -> str:
    """Best-effort 'which binary' for a shell command, ignoring env prefixes."""
    toks = cmd.strip().split()
    i = 0
    while i < len(toks) and ("=" in toks[i] and not toks[i].startswith("-")):
        i += 1  # skip VAR=val prefixes
    return toks[i] if i < len(toks) else ""


def _normalize_cmd(cmd: str) -> str:
    """Normalize a bash command for duplicate detection: strip, collapse whitespace."""
    return " ".join(cmd.split())


def _parse_one(path: Path, tool_uses: dict, results: list) -> int:
    """Parse a transcript file into shared tool_uses/results. Returns assistant_turns."""
    assistant_turns = 0
    for entry in _iter_lines(path):
        if entry.get("type") == "assistant":
            assistant_turns += 1
        msg = entry.get("message", entry)
        for block in _walk_blocks(msg):
            if block.get("type") == "tool_use":
                name = block.get("name", "?")
                inp = block.get("input") or {}
                cmd = ""
                if isinstance(inp, dict):
                    cmd = inp.get("command") or inp.get("file_path") or ""
                tool_uses[block.get("id")] = {
                    "name": name,
                    "command": cmd,
                    "input": inp if isinstance(inp, dict) else {},
                }
            elif block.get("type") == "tool_result":
                rid = block.get("tool_use_id")
                txt = _text_of(block.get("content"))
                if "is_error" in block:
                    err = bool(block["is_error"])
                else:
                    err = bool(CONFIG["error_text_re"].search(txt))
                rejected = bool(CONFIG["rejection_text_re"].search(txt))
                results.append({"id": rid, "is_error": err, "rejected": rejected, "text": txt})
    return assistant_turns


def parse_transcript(path: Path) -> dict:
    """Parse a session transcript (and its subagents) into tool/result records."""
    tool_uses: dict = {}
    results: list = []

    assistant_turns = _parse_one(path, tool_uses, results)

    # Merge subagent transcripts at <project>/<session-id>/subagents/agent-*.jsonl
    subagents_dir = path.parent / path.stem / "subagents"
    subagent_files = sorted(subagents_dir.glob("agent-*.jsonl")) if subagents_dir.is_dir() else []
    for sub in subagent_files:
        assistant_turns += _parse_one(sub, tool_uses, results)

    return {
        "tool_uses": tool_uses,
        "results": results,
        "assistant_turns": assistant_turns,
        "subagent_count": len(subagent_files),
    }


# ----------------------------------------------------------------------------
# Scoring
# ----------------------------------------------------------------------------
def _subscore(rate: float, ref_rate: float) -> float:
    """Compute a 0–100 subscore: 100*(1 - rate/ref_rate), clamped to [0, 100]."""
    return 100.0 * max(0.0, 1.0 - rate / ref_rate)


def score_session(parsed: dict) -> dict:
    """Score a parsed transcript into a 0-100 result with subscores and detail."""
    tool_uses = parsed["tool_uses"]
    results = parsed["results"]
    w = CONFIG["weights"]
    ref = CONFIG["ref_rates"]

    # --- errors, attributed to the command that produced them ---
    errors = []
    rejections = []
    for r in results:
        tu = tool_uses.get(r["id"], {})
        label = tu.get("command") or tu.get("name") or "?"
        snippet = r["text"].strip().splitlines()[0][:160] if r["text"].strip() else ""
        if r.get("rejected"):
            rejections.append({"tool": tu.get("name", "?"), "label": label[:120]})
        elif r.get("is_error") or (
            "is_error" not in r and bool(CONFIG["error_text_re"].search(r.get("text", "")))
        ):
            errors.append({"tool": tu.get("name", "?"),
                           "label": label[:120],
                           "snippet": snippet})

    # --- duplicate identical commands (normalized) ---
    bash_cmds_raw = [tu["command"]
                     for tu in tool_uses.values()
                     if tu["name"] == "Bash" and tu["command"].strip()]
    bash_cmds = [_normalize_cmd(c) for c in bash_cmds_raw]
    cmd_counts = Counter(bash_cmds)
    duplicates = {c: n for c, n in cmd_counts.items() if n > 1}

    # --- repeated file reads ---
    read_paths = [tu["input"].get("file_path", "")
                  for tu in tool_uses.values()
                  if tu["name"] == "Read" and tu["input"].get("file_path")]
    read_counts = Counter(read_paths)
    repeat_reads = {p: n for p, n in read_counts.items() if n > 1}

    # --- scriptability: same binary hammered raw many times ---
    binaries = Counter(_first_token(c) for c in bash_cmds if _first_token(c))
    clusters = {b: n for b, n in binaries.items()
                if n >= CONFIG["scriptability_threshold"]}

    # --- activity counts ---
    total_tool_calls = len(tool_uses)
    bash_calls = len(bash_cmds)
    read_calls = len(read_paths)

    # --- low activity guard ---
    if total_tool_calls < CONFIG["min_tool_calls"]:
        no_issues = not errors and not rejections
        score = 100 if no_issues else 60
        grade = next(g for floor, g in CONFIG["grades"] if score >= floor)
        subscores = {k: 100.0 for k in w}
        rates = {
            "errors": (len(errors), max(total_tool_calls, 1)),
            "rejections": (len(rejections), max(total_tool_calls, 1)),
            "duplicate_commands": (sum(n - 1 for n in duplicates.values()), max(bash_calls, 1)),
            "repeated_reads": (sum(n - 1 for n in repeat_reads.values()), max(read_calls, 1)),
            "scriptability": (len(clusters), max(len(binaries), 1)),
        }
        return {
            "score": score,
            "grade": grade,
            "low_activity": True,
            "subscores": subscores,
            "weights": w,
            "rates": rates,
            "metrics": {
                "assistant_turns": parsed["assistant_turns"],
                "total_tool_calls": total_tool_calls,
                "bash_calls": bash_calls,
                "read_calls": read_calls,
                "tool_errors": len(errors),
                "user_rejections": len(rejections),
                "subagent_count": parsed.get("subagent_count", 0),
            },
            "detail": {
                "errors": errors,
                "rejections": rejections,
                "duplicates": duplicates,
                "repeat_reads": repeat_reads,
                "binary_clusters": clusters,
            },
        }

    # --- compute rates ---
    dup_extra = sum(n - 1 for n in duplicates.values())
    read_extra = sum(n - 1 for n in repeat_reads.values())
    unique_binaries = len(binaries)

    rates = {
        "errors": (len(errors), total_tool_calls),
        "rejections": (len(rejections), total_tool_calls),
        "duplicate_commands": (dup_extra, max(bash_calls, 1)),
        "repeated_reads": (read_extra, max(read_calls, 1)),
        # scriptability rate: fraction of unique binaries that are "over-hammered".
        # Normalizing by unique_binaries rather than total calls makes a wide toolset
        # look better than hammering a single binary repeatedly.
        "scriptability": (len(clusters), max(unique_binaries, 1)),
    }

    # --- subscores per category ---
    subscores = {}
    for cat, (numerator, denominator) in rates.items():
        rate = numerator / denominator
        subscores[cat] = _subscore(rate, ref[cat])

    # --- weighted average ---
    weighted_avg = sum(w[cat] * subscores[cat] for cat in w)

    # --- disaster guard: catastrophic in one category → cap the overall ---
    min_sub = min(subscores.values())
    disaster_cap = min_sub + CONFIG["disaster_cap_addend"]
    overall = min(weighted_avg, disaster_cap)

    score = max(0, min(100, round(overall)))
    grade = next(g for floor, g in CONFIG["grades"] if score >= floor)

    return {
        "score": score,
        "grade": grade,
        "low_activity": False,
        "subscores": {k: round(v, 1) for k, v in subscores.items()},
        "weights": w,
        "rates": rates,
        "metrics": {
            "assistant_turns": parsed["assistant_turns"],
            "total_tool_calls": total_tool_calls,
            "bash_calls": bash_calls,
            "read_calls": read_calls,
            "tool_errors": len(errors),
            "user_rejections": len(rejections),
            "subagent_count": parsed.get("subagent_count", 0),
        },
        "detail": {
            "errors": errors,
            "rejections": rejections,
            "duplicates": duplicates,
            "repeat_reads": repeat_reads,
            "binary_clusters": clusters,
        },
    }


# ----------------------------------------------------------------------------
# Suggestions — ranked by impact (points lost = weight × (100 − subscore))
# ----------------------------------------------------------------------------
def build_suggestions(scored: dict) -> list:
    """Turn scoring detail into actionable, human-readable suggestions, impact-ranked."""
    d = scored["detail"]
    subscores = scored.get("subscores", {})
    weights = scored.get("weights", CONFIG["weights"])
    rates = scored.get("rates", {})
    m = scored["metrics"]

    # Build candidate suggestions with their impact score
    candidates = []

    if m["tool_errors"]:
        num, den = rates.get("errors", (m["tool_errors"], 1))
        impact = weights.get("errors", 0) * (100 - subscores.get("errors", 100))
        top = d["errors"][0]["label"] if d["errors"] else "n/a"
        candidates.append((impact, "[Errors] "
            f"{m['tool_errors']} tool error(s) in {den} calls. "
            "The agent should capture and read failure output once, not retry blind. "
            f"Top offender: {top}"))

    if m.get("user_rejections"):
        impact = weights.get("rejections", 0) * (100 - subscores.get("rejections", 100))
        top = d["rejections"][0]["label"] if d["rejections"] else "n/a"
        candidates.append((impact, "[Rejections] "
            f"{m['user_rejections']} tool call(s) rejected by the user. "
            "Confirm intent before risky or irreversible actions. "
            f"Top offender: {top}"))

    dup_extra = sum(n - 1 for n in d["duplicates"].values())
    if dup_extra:
        impact = weights.get("duplicate_commands", 0) * (100 - subscores.get("duplicate_commands", 100))
        worst_cmds = sorted(d["duplicates"].items(), key=lambda x: -x[1])[:3]
        for cmd, n in worst_cmds:
            candidates.append((impact / max(len(worst_cmds), 1),
                f"[Duplicates] Command run {n}x identically: `{cmd[:80]}`. "
                "Cache the result or hoist it into a setup step."))

    read_extra = sum(n - 1 for n in d["repeat_reads"].values())
    if read_extra:
        impact = weights.get("repeated_reads", 0) * (100 - subscores.get("repeated_reads", 100))
        worst_reads = sorted(d["repeat_reads"].items(), key=lambda x: -x[1])[:3]
        for path, n in worst_reads:
            candidates.append((impact / max(len(worst_reads), 1),
                f"[Repeat reads] Re-read `{os.path.basename(path)}` {n}x. "
                "Pin key files into context once up front."))

    if d["binary_clusters"]:
        impact = weights.get("scriptability", 0) * (100 - subscores.get("scriptability", 100))
        worst_bins = sorted(d["binary_clusters"].items(), key=lambda x: -x[1])[:3]
        for binary, n in worst_bins:
            candidates.append((impact / max(len(worst_bins), 1),
                f"[Scriptability] `{binary}` called {n}x raw. "
                f"When >{CONFIG['scriptability_threshold']} related shell steps, "
                "write a reusable script or batch into one call."))

    # Sort by impact descending, take top 8
    candidates.sort(key=lambda x: -x[0])
    out = [msg for _, msg in candidates[:8]]

    if not out:
        out.append("Clean run. No structural waste detected.")
    return out


def headline(scored: dict) -> str:
    """Compact one-line summary, e.g. '84 B · 2 err · 1 dup'."""
    m = scored["metrics"]
    bits = [f"{scored['score']} {scored['grade']}"]
    if m["tool_errors"]:
        bits.append(f"{m['tool_errors']} err")
    if m.get("user_rejections"):
        bits.append(f"{m['user_rejections']} rej")
    dups = sum(n - 1 for n in scored["detail"]["duplicates"].values())
    if dups:
        bits.append(f"{dups} dup")
    return " · ".join(bits)


# ----------------------------------------------------------------------------
# Project label / first-prompt helpers (for leaderboard display)
# ----------------------------------------------------------------------------

def _clean_snippet(text: str) -> str:
    """Strip XML-ish tags and collapse whitespace for display."""
    text = _XML_TAG_RE.sub(" ", text)
    return _MULTI_SPACE_RE.sub(" ", text).strip()


def _clean_user_text(text: str) -> str:
    """
    Strip local-command boilerplate from a user message text and return
    the remaining real content. Returns empty string if nothing real found.
    """
    # Remove caveat prefix paragraph
    text = _CAVEAT_PREFIX_RE.sub("", text)
    # Remove full infra XML blocks
    text = _INFRA_TAG_RE.sub("", text)
    # Remove any stray opening/closing infra tags
    text = _INFRA_OPEN_TAG_RE.sub("", text)
    # Collapse whitespace
    text = _MULTI_SPACE_RE.sub(" ", text).strip()
    return text


def humanize_project(raw: str) -> str:
    """Slug like '-Users-allannapier-code-pelai-api' -> 'pelai-api'."""
    name = raw
    if name.startswith("-"):
        name = name[1:]
    elif name.startswith("s-"):
        name = name[2:]
    if "-code-" in name:
        name = name.split("-code-", 1)[1]
    elif "-" in name:
        parts = name.split("-")
        name = "-".join(parts[-2:]) if len(parts) >= 2 else name
    return name or raw


def first_prompt(path: Path, max_lines: int = 200) -> str:
    """
    Return the first real human prompt from a transcript, for labelling.

    Skips lines that are local-command boilerplate (Caveat: prefix, or
    lines consisting only of <command-name>, <system-reminder>, etc. tags).
    Strips those infrastructure elements from mixed messages and returns
    the remaining text if non-empty. Falls back to the raw cleaned text if
    nothing better is found within max_lines.
    """
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            for _ in range(max_lines):
                line = fh.readline()
                if not line:
                    break
                try:
                    e = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if e.get("type") != "user":
                    continue
                content = (e.get("message") or {}).get("content")

                texts = []
                if isinstance(content, str):
                    texts = [content]
                elif isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "text":
                            texts.append(str(b.get("text", "")))

                for raw_text in texts:
                    cleaned = _clean_user_text(raw_text)
                    if cleaned:
                        return cleaned

    except OSError:
        pass
    return ""


def evaluate_file(path: Path) -> Optional[dict]:
    """Parse + score a single transcript, returning a display-ready record."""
    try:
        scored = score_session(parse_transcript(path))
    except Exception:
        return None
    try:
        mtime = path.stat().st_mtime
    except OSError:
        mtime = 0.0
    raw_project = path.parent.name
    return {
        "session_id": path.stem,
        "project": raw_project,
        "project_label": humanize_project(raw_project),
        "mtime": mtime,
        "date": datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M") if mtime else "",
        "prompt": first_prompt(path)[:120],
        "score": scored["score"],
        "grade": scored["grade"],
        "low_activity": scored.get("low_activity", False),
        "headline": headline(scored),
        "metrics": scored["metrics"],
        "subscores": scored["subscores"],
        "weights": scored["weights"],
        "rates": scored["rates"],
        "suggestions": build_suggestions(scored),
        "detail": scored["detail"],
    }
